name: "aion49"
services:
  aion49-database:
    container_name: aion49-database
    image: mysql:5.7
    networks:
      aion49-network:
        ipv4_address: ${DB_HOST}
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./.mysql/:/var/lib/mysql
    restart: ${SERVER_RESTART}
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'MYSQL_PWD=${DB_PASS} mysqladmin ping'
        ]
      interval: 10s
      timeout: 2s
      retries: 10
  phpmyadmin:
    container_name: aion49-dbadmin
    image: phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: ${SERVER_RESTART}
    environment:
      - PMA_HOST=aion49-database
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASS}
      - UPLOAD_LIMIT=300M
    profiles: []
    env_file:
      - ./.env
    networks:
      aion49-network:
        ipv4_address: ${NETWORK_SUBNET}.7
    depends_on:
      aion49-database:
        condition: service_healthy
        restart: true
      aion49-server:
        condition: service_healthy
        restart: true
  aion49-server:
    container_name: aion49-server
    build: .
    ports:
      - "10241:10241"
      - "9021:9021"
      - "${GAME_PORT}:${GAME_PORT}"
      - "${GAMESERVER_PORT}:${GAMESERVER_PORT}"
      - "${LOGIN_PORT}:${LOGIN_PORT}"
    env_file:
      - ".env"
    depends_on:
      aion49-database:
        condition: service_healthy
        restart: true
    links:
      - "aion49-database"
    restart: ${SERVER_RESTART}
    networks:
      aion49-network:
        ipv4_address: ${NETWORK_SUBNET}.8
    healthcheck:
      test: 'cat /aion/AL-Game/build/dist/AL-Game/log/console.log | grep "Connected to LoginServer"'
      timeout: 10s
      retries: 10
networks:
  aion49-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}.0/24
          gateway: ${NETWORK_SUBNET}.1
